### ISSUE TITLE
Infof doesn't respect Printf format arguments

### ISSUE THREAD

**Issue by jlordiales** [sethvargo/go-githubactions#15]
`action.Infof("foo %s", "bar")` prints `foo %s [bar]`

I'm guessing https://github.com/sethvargo/go-githubactions/blob/ca29fef545f20f2d76de1e3ddda18d668a98d3b8/actions.go#L279 should use `Fprintf` instead of `Fprintln`

**Comment by sethvargo** [comment]
Probably. Do you want to submit a PR?

**Comment by jlordiales** [comment]
Yeap, will do tomorrow!
