### ISSUE TITLE
Expose a field in `Action` with `getenvFunc`.

### ISSUE THREAD

**Issue by dhermes** [sethvargo/go-githubactions#18]
I am happy to do the work here, I just wanted sign off before sending a PR. I'm also happy to conform to your preferences, some possible design choices:

- Make `Action.GetEnv` an exported field **OR** make `Action.getEnv` unexported
- Support an options pattern in `New()` so that `GetEnv` can be optionally set **OR** provide a `NewWithGetEnv()` function similar to `NewWithWriter()` **OR** provide a `Action.WithGetEnv()` method for setting the field
- Check if `Action.GetEnv` is `nil` before usage and fallback to `os.Getenv` (would require a wrapper method) **OR** trust that `Action.GetEnv: os.Getenv` will be the default set in `New()` and leave it at that

----

**Motivation**: This makes it somewhat easier to write unit tests for GitHub actions.

Just now I am testing an "input parsing" function and ended up defining

```go
type getInputer interface {
	GetInput(string) string
}

func NewFromInputs(action getInputer) (*Config, error) {
	// ...
}
```

so that in my tests I can use

```go
type GetInputMap struct {
	Map map[string]string
}

func (gim GetInputMap) GetInput(i string) string {
	return gim.Map[i]
}
```

**Comment by sethvargo** [comment]
Hey @dhermes 

- I think supporting variadic options in `New` is the best approach. That would also allow us to deprecate `NewWithWriter` and create a `WithWriter` option.

- I'm not sure I understand your last bullet - can you tell me more?

**Comment by dhermes** [comment]
> I'm not sure I understand your last bullet - can you tell me more?

I.e. provide guard rails with something like

```go
func (c Action) Getenv(key string) string {
	if c.getenv != nil {
		return c.getenv(key)
	}
	return os.Getenv(key)
}
```

vs. just using the unexported field directly:

```go
func (c *Action) IssueFileCommand(cmd *Command) error {
	return c.issueFileCommand(cmd, c.getenv)
}
```

and trusting that we have sane defaults in `New()`

```go
func New(opts ...Option) *Action {
	a := &Action{w: os.Stdout, getenv: os.Getenv}
	for _, opt := range opts {
		opt(a)
	}
	return a
}

```

**Comment by sethvargo** [comment]
Ah thanks! I'd prefer to ensure we have defaults in `New` and just delegate.

**Comment by dhermes** [comment]
Good deal. PR coming in shortly.
