### ISSUE TITLE
[FEATURE] Add support for `Action.GitHubContext()`

### ISSUE THREAD

**Issue by dhermes** [sethvargo/go-githubactions#24]
My original motivation was to have a method like

```go
action.GitHubContext().Labels()
```

and have this method check `GITHUB_EVENT_NAME == "pull_request"` and then (if equal) would parse `GITHUB_EVENT_PATH` and return the equivalent of `${{ github.event.pull_request.labels }}`.

In general for an action it may be nice to have access to things like `GITHUB_REF` to provide programmatic defaults vs. hardcoded values in `action.yml`.

----

I captured an [example][1] `create` event (also a `push` [event][2]) and we have environment variables:

```
GITHUB_ACTION=run1
GITHUB_ACTIONS=true  # Not in `${{ github }}` context
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=dhermes
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_735e47f8-a348-42e3-ba30-cafcd54f1c9b
GITHUB_EVENT_NAME=create
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_HEAD_REF=
GITHUB_JOB=ci
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_735e47f8-a348-42e3-ba30-cafcd54f1c9b
GITHUB_REF=refs/heads/trigger-many
GITHUB_REPOSITORY=dhermes/bezier
GITHUB_REPOSITORY_OWNER=dhermes
GITHUB_RETENTION_DAYS=90
GITHUB_RUN_ID=818468044
GITHUB_RUN_NUMBER=2
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=be377e49cf9c2bb751374cc6ee770fee98df3293
GITHUB_WORKFLOW=Trigger Many
GITHUB_WORKSPACE=/home/runner/work/bezier/bezier
```

where the equivalent `${{ github }}` context (keys re-ordered alphabetically) is

```json
{
    "action": "run2",
    "action_ref": "",
    "action_repository": "",
    "actor": "dhermes",
    "api_url": "https://api.github.com",
    "base_ref": "",
    "env": "/home/runner/work/_temp/_runner_file_commands/set_env_735e47f8-a348-42e3-ba30-cafcd54f1c9b",
    "event": {...},
    "event_name": "create",
    "event_path": "/home/runner/work/_temp/_github_workflow/event.json",
    "graphql_url": "https://api.github.com/graphql",
    "head_ref": "",
    "job": "ci",
    "path": "/home/runner/work/_temp/_runner_file_commands/add_path_735e47f8-a348-42e3-ba30-cafcd54f1c9b",
    "ref": "refs/heads/trigger-many",
    "repository": "dhermes/bezier",
    "repositoryUrl": "git://github.com/dhermes/bezier.git", // Not in GITHUB_* env vars
    "repository_owner": "dhermes",
    "retention_days": "90",
    "run_id": "818468044",
    "run_number": "2",
    "server_url": "https://github.com",
    "sha": "be377e49cf9c2bb751374cc6ee770fee98df3293",
    "token": "***", // Not in GITHUB_* env vars
    "workflow": "Trigger Many",
    "workspace": "/home/runner/work/bezier/bezier"
}
```

We can try to leverage something like https://github.com/google/go-github to parse the contents of the file in `GITHUB_EVENT_PATH`.

[1]: https://github.com/dhermes/bezier/runs/2522739333?check_suite_focus=true
[2]: https://github.com/dhermes/bezier/runs/2522739340?check_suite_focus=true

**Comment by dhermes** [comment]
> I think those are all available as envvars, aren't they?

Yeah, the supported env vars are in the section that starts with

```
GITHUB_ACTION=run1
GITHUB_ACTIONS=true  # Not in `${{ github }}` context
GITHUB_ACTION_REF=
...
```

Are you mentioning that to say it's not worth adding to `Action` since users can just directly grab from the environment variables?

> I'm also opposed to taking any dependencies on third-party libraries (sorry!)

I think that's OK. This package could still provide "minimal" structs for parsing the JSON stored in `GITHUB_EVENT_PATH` and still end up with a nice API. (And those structs could grow organically as needed, depending on the use case.)

**Comment by sethvargo** [comment]
> Are you mentioning that to say it's not worth adding to Action since users can just directly grab from the environment variables?

Yea, especially since I think that API is subject to change by GitHub too.

**Comment by dhermes** [comment]
I'm wondering why this argument wouldn't apply to reading env. vars. of the form `INPUT_FOO` instead of using `Action.GetInput()`.

Some of these values (in  particular `GITHUB_ACTOR`, `GITHUB_EVENT_NAME` and `GITHUB_REF`) are ones I reach for quite often when writing a new action.

> that API is subject to change by GitHub too.

That makes it more challenging, but in some sense if we were to ship a method on `Action` / custom type for this, the implementation details are opaque to users of `github.com/sethvargo/go-githubactions` and they get the same convenience of being able to do `${{ github.actor }}` in a workflow (action author != workflow author always). (Of course this is challenging for old versions of this package, but this is true of any library written against an API that is a moving target.)

**Comment by dhermes** [comment]
@sethvargo just got the stale notification. Any thoughts on my latest comment?

We could try to scope it to be quite small initially (e.g. only support a handful of things like `GITHUB_ACTOR`, `GITHUB_EVENT_NAME`, `GITHUB_JOB`, `GITHUB_REF`) and then build out from there?
