### ISSUE TITLE
Getting commit message from GITHUB_CONTEXT

### ISSUE THREAD

**Issue by dkirrane** [sethvargo/go-githubactions#29]
I'm looking for a way to get the commit message. Is this possible?

Currently I do the following, but it's verbose in yaml
```
      - run: echo "COMMIT_MESSAGE=${{ github.event.workflow_run.head_commit.message }}" >> $GITHUB_ENV
        shell: bash
        if: github.event_name == 'workflow_run'

      - run: echo "COMMIT_MESSAGE=${{ github.head_ref }}" >> $GITHUB_ENV
        shell: bash
        if: github.event_name == 'pull_request'

      - run: echo "COMMIT_MESSAGE=${{ github.event.commits[0].message }}" >> $GITHUB_ENV
        shell: bash
        if: github.ref == 'refs/heads/main'
```

**Comment by sethvargo** [comment]
Is this question about the Go library? I don't see anything about go-githubactions in your query. For general GitHub Actions questions, please ask GitHub (I'm just an OSS developer :))

If I were you, I would probably just checkout the code and use that git CLI:

    git log -1 --pretty=format:"%s"
    
That should work regardless of push, pull request, tag, etc.
