### ISSUE TITLE
Support for getting the "context that the current action is being run in"

### ISSUE THREAD

**Issue by BattleBas** [sethvargo/go-githubactions#3]
Your article was a great resource for helping get started with GitHub actions using Go! Thanks!

At the moment this package mainly supports the features that [@actions/core](https://github.com/actions/toolkit/tree/master/packages/core) has.

I was wondering if you had plans on supporting the features that [@actions/github](https://github.com/actions/toolkit/tree/master/packages/github) provides? From what I read, the context information this package provides can mainly be found in the events.json file (The path of it you can get with in the environment variable `GITHUB_EVENT_PATH`)

I would be happy to take a stab at it and make a pull request, but thought I'd ask first to see what your plans were. The way that GitHub has the toolkit repository structured is having multiple "packages" within one repo, so wasn't sure if that is what you were envisioning in copying as well. Also probably using another name then "context" to describe the events payload might be a good idea to prevent overloading the meaning of that word.

Thanks!

**Comment by sethvargo** [comment]
I think you'd just want to use a Go GitHub client like https://github.com/google/go-github.

**Comment by BattleBas** [comment]
The Go GitHub client is definitely useful but it doesn't look like the does what @actions/github does, it helps parse the events payload described here: https://developer.github.com/v3/activity/events/types/

**Comment by sethvargo** [comment]
https://github.com/google/go-github/blob/master/github/event.go ?

**Comment by BattleBas** [comment]
*facepalm* I should have read the documentation better, thank you for pointing this out!
