### ISSUE TITLE
Testing `SetOutput` calls

### ISSUE THREAD

**Issue by wjam** [sethvargo/go-githubactions#53]
I'm writing GitHub actions which make use of this library and want to include the `SetOutput` calls within the tests, so that the key/value being outputted can be asserted on. Do you know if there's any libraries that can parse the GitHub environment file which include `<<`? Or if a helper function can be added to the library to parse out a GitHub environment file?

**Comment by sethvargo** [comment]
I'm not sure what you mean by "which include `<<`", but [here's a test](https://github.com/sethvargo/go-githubactions/blob/be6c1049c3263d059ae40ff93765e8522a84be28/actions_test.go#L73-L108) that shows how to test the values that are created via `SetOutput`.

**Comment by schmidtw** [comment]
Similar to the `WithWriter()` option, it would be quite nice if there was an option like `WithFileWriter(file string, w io.Write)` where we can pass in a buffer to be filled & the name of the file the buffer represents ... `GITHUB_ENV` for example.  This means we don't need to create a directory, write to disc & clean up when testing.
