### ISSUE TITLE
Support for actions artifact uploads

### ISSUE THREAD

**Issue by nfx** [sethvargo/go-githubactions#56]
If we're writing actions in Go, it'll be great to get this into this library as well. APIs are not documented, though:
- https://github.com/actions/toolkit/tree/main/packages/artifact/src/internal/upload
- https://github.com/actions/upload-artifact/issues/180#issuecomment-1086306269
- https://github.com/actions/upload-artifact/issues/180#issuecomment-1301521285

**Comment by sethvargo** [comment]
Hi @nfx - my general rule is that I only add support for things that GitHub has publicly documented. I've been burned twice by features that exist in the Node.js libraries that then change or get removed without warning.

If you'd like to see this in go-githubactions, the first step would be to open a discussion/feature with GitHub to officially document this functionality. Sorry!
