### ISSUE TITLE
Upload Artifact support?

### ISSUE THREAD

**Issue by StevenACoffman** [sethvargo/go-githubactions#7]
This library is really great, as I much prefer to have pure Go implementations! However, one step that I'm still using in JavaScript, and related to the githubactions api, is [persisting workflow data using artifacts](https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts) using the [actions/upload-artifact@v2](https://github.com/marketplace/actions/upload-a-build-artifact) action.

I found that the [upload-artifact action source code](https://github.com/actions/upload-artifact/blob/master/src/upload-artifact.ts) uses the [ @actions/artifact](https://github.com/actions/toolkit/tree/master/packages/artifact) library.

I was curious if this is something that you might consider adding to this library.

**Comment by sethvargo** [comment]
Hi @StevenACoffman - I think that'd be better off as a separate library (much like the node.js counterparts). This is most akin to "core".

**Comment by StevenACoffman** [comment]
Yeah, I think you're right. I'd prefer to keep every github action tightly focused and lightweight. I'm going to close this issue, but if I get that implemented in Go, I'll leave a comment linking to it.
