### ISSUE TITLE
Set ENV and Add Path commands deprecated

### ISSUE THREAD

**Issue by polothy** [sethvargo/go-githubactions#9]
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Probably need to write to these new files: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

Can probably port what was done in the `@actions/core` package:

Add path https://github.com/actions/toolkit/blob/4f7fb6513a355689f69f0849edeb369a4dc81729/packages/core/src/core.ts#L63-L75

Set env https://github.com/actions/toolkit/blob/4f7fb6513a355689f69f0849edeb369a4dc81729/packages/core/src/core.ts#L35-L53

**Comment by ashutoshgngwr** [comment]
@polothy @sethvargo I have a fix for this in https://github.com/ashutoshgngwr/go-githubactions/commit/fdb2783539d43c26874106aa3b12ad6849f9ac20 but the commit builds on top of #10.
